### PR TITLE
Add logo for publicity

### PR DESCRIPTION
**Pull request by ItzSwirlz**

### CODE REVIEW

**Comment by ItzSwirlz** [comment]
ah.. github uses a different render for images centering

**Review by xyzeva — CHANGES_REQUESTED** [review]
Maybe make it a bit less small? It seems a bit occupying from the actual point.

**Review by xyzeva — CHANGES_REQUESTED** [review]
Possibly put it above the header, looks a bit weird like this, 
Also maybe center the original header just below the logo

**Comment by ItzSwirlz** [comment]
> Possibly put it above the header, looks a bit weird like this, Also maybe center the original header just below the logo

Put what above the header: the logo as a whole, the "FRACTUREISER" text?

**Comment by xyzeva** [comment]
logo as a whole, you can remove the header aswell.

**Comment by ItzSwirlz** [comment]
i want to confirm, by "you can remove the header as well", take out this line:
```
# Modded Minecraft Malware "fractureiser"
```

you sure?

**Comment by xyzeva** [comment]
The logo already says fractureiser, what i meant is make the "Modded Minecraft Malware" a subheader in the image, or just a subheader as a `h3` centered.

**Comment by ItzSwirlz** [comment]
I also tried out this inner shadow on the text, do you like it?

image

**Comment by xyzeva** [comment]
Looks pretty good, but maybe not for the subheader.

**Review by xyzeva — APPROVED** [review]
LGTM

**Comment by ItzSwirlz** [comment]
It might still be a bit tiny, should I try scaling it up

**Comment by ItzSwirlz** [comment]
image

The current branch proposed is 1/4 of what I originally worked with (left), the right is 1/2

**Comment by ItzSwirlz** [comment]
> 1/2 Looks better, I'd say do it.

Okay, I'm going to do a full rebase to prevent flooding the logs

**Review by xyzeva — CHANGES_REQUESTED** [review]
Change with @unascribed's [logo](https://unascribed.com/f/307f252c/fractureiser.opt.svg)

**Review by xyzeva — APPROVED** [review]
LGTM

**Pull request merged**
