### PR TITLE
Possible sandboxing of MacOS

### PR DESCRIPTION
**Pull request by RayBytes**
Adding an idea for sandboxing MacOS using seabelt

### CODE REVIEW

**Comment by RayBytes** [comment]
> I have MacOS so I can try testing things like this, I don't know how to sandboxer works but as long as it doesn't interfere with anything game related it sounds good

yup I also use MacOS, thats how I thought about it. Its a feature in XCode but im pretty sure you can also use it in terminal via `sandbox-exec`

also looking more into it, I think it does seem possible to only allow a app to access certain networks! This could allow us to basically have a fully sandboxes minecraft. You can create a sandbox profile, and using `sandbox-exec` sandbox minecraft completely with that profile, and all people would have to do is download the profile and run it. _at least thats hot it seems_

**Comment by Janmm14** [comment]
@RayBytes given ppl want to connect to a bunch of different multiplayer servers, how would that work out? and what happens when ms changes ips of the auth servers etc

**Comment by ItzSwirlz** [comment]
Also: does it show you specifically what IP/connection it's trying to connect to?

**Comment by RayBytes** [comment]
regarding the multiplayer servers - honestly, did not think about that. If minecraft is to be only singeplayer then we can fully sandbox it and disable network access, we can still allow localhost stuff though so people can host/connect LAN. otherwise if we want to include multiplayer then we would have to do some hacky mod or something to get servers added to the server list and allow those servers. If MS changes IPs of the auth servers wont matter if we restrict it to only singleplayer, but if we want multiplayer then we would just have to know the new IPs of the auth servers and change it in the config.. though I do not think that happens often.

> Also: does it show you specifically what IP/connection it's trying to connect to?
wdym by this?

**Comment by williewillus** [comment]
sure

**Comment by makindotcc** [comment]
I was working on sandboxing proprietary minecraft client (lunarclient) on macOS using sandboxexec - https://github.com/makindotcc/sandboxexec_LunarClient/blob/sandbox-config/lunarlauncher/cmd/lunar.sb
It is not perfect (yet) since there are some hardcoded values like: 
```
(allow iokit-open
    ;; AMD Radeon 5300, dunno how to make these rules unique for all GPUs
    (iokit-registry-entry-class "AMDRadeonX6000_AMDAccelDevice")
    (iokit-registry-entry-class "AMDRadeonX6000_AMDAccelSharedUserClient")
    (iokit-registry-entry-class "AMDRadeonX6000_AMDGFX10GLContext")
  ```
but I think it is possible to polish it somehow. I could look into it again and try to finish it if needed.

**Pull request merged**
