### PR TITLE
Remove broken hyperlinks [docs/tech.md]

### PR DESCRIPTION
**Pull request by ItsNiceCraft**

### CODE REVIEW

**Comment by ItsNiceCraft** [comment]
Looks like my formatter messed the spacing up, hold on

**Comment by neonspectra** [comment]
It's generally poor form to leave hyperlink to IOCs clickable; was under the impression that the linked files are intentionally mangled. 

I made a PR (#29) with an alternative form for these to standardise the formatting but ensure they're not clickable.

**Comment by ItsNiceCraft** [comment]
I agree with you but don't think this needs a new pr. Removed the https links again.

**Comment by unascribed** [comment]
Superseded by #33

**Pull request closed without merging**
