### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Nitrrine**
- [X] Main README
- [x] credits.md
- [x] user.md
- [x] tech.md
- [x] timeline.md
- [x] 2023-06-08-meeting.md
- [x] stages.png (thanks, [vadcx](https://github.com/vadcx)!)
- [x] flowchart.png
- [x] sandboxfile.png
- [x] localappdata.png

Also thanks [vadcx](https://github.com/vadcx) for significant grammar refactoring & stages.png translation!

### CODE REVIEW

**Comment by vadcx** [comment]
I will take over stages.png translation

**Comment by Nitrrine** [comment]
> I will take over stages.png translation

Nice! You can make PR in my fork

**Comment by Nitrrine** [comment]
@vadcx, can you review files?

**Comment by vadcx** [comment]
I approve once https://github.com/Nitrrine/fractureiser/pull/3 is merged in.

The only thing I didn't do is look at are the meeting notes, imho not that important.

**Comment by Nitrrine** [comment]
Merge conflicts resolved, ready to merge

**Comment by vadcx** [comment]
Hey 3 months have passed... Do I need to ping and annoy someone certain on Discord for the outstanding PRs to be merged? This one here only needs a single click, no merge conflicts left.

**Comment by unascribed** [comment]
Well, better late than never. Sorry, during the fractureiser situation we all got pushed past our limits and basically dropped it completely once things seemed to have run their course. Even months later we're still exhausted, especially after our entire team also helping with BlanketCon.

**Review by unascribed — APPROVED** [review]
Machine translation spot check as bare minimum due diligence looks OK ­— thanks for your work on this, and sorry for the delay!

**Comment by vadcx** [comment]
Thanks! Yeah I know what it's like to work mindlessly for an urgent project... don't we all? :) To me this fractureiser event marks a shift in malware distribution and development, I had wanted to write a generalized post about this development for a wider IT community. Now I will (eventually™)

**Pull request merged**
