### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Leclowndu93150**
i specified which launchers were affected

### CODE REVIEW

**Comment by Leclowndu93150** [comment]
smh

**Comment by AwesomeKalin** [comment]
It can be launchers that use are written in java and have a .jar file on the filesystem as ALL jar files get infected

**Comment by std-cin** [comment]
Every launcher is affected, it's not launcher specific

**Comment by Janmm14** [comment]
the malware does look for files containing credentials of the launchers he mentioned tho.

**Pull request closed without merging**
